import { Notice, CalendarEvent, Assignment, AppUser } from './types';

function daysFromNow(days: number): Date {
  const d = new Date();
  d.setDate(d.getDate() + days);
  d.setHours(0, 0, 0, 0);
  return d;
}

function daysAgo(days: number): Date {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d;
}

export const SEED_NOTICES: Omit<Notice, 'id'>[] = [
  // ACADEMIC (5)
  {
    title: 'Mid-Semester Exam Schedule Released',
    body: 'The mid-semester examination schedule for all B.Tech and BBA branches has been released. Exams begin April 14. Download the complete timetable from the exam cell website. Seating arrangements will be shared 2 days before each exam.',
    category: 'Academic',
    tags: ['ALL'],
    urgency: 'Urgent',
    postedBy: 'Dr. R.K. Sharma',
    postedAt: daysAgo(1),
    expiryDate: daysFromNow(21),
    isPinned: true,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Assignment Submission Deadline Extended',
    body: 'Due to the upcoming festival break, the deadline for Data Structures (CS301) assignments has been extended to April 10. Submit via the department portal. Late submissions will not be accepted.',
    category: 'Academic',
    tags: ['CSE-3', 'CSE-4'],
    urgency: 'Important',
    postedBy: 'Prof. Meena Gupta',
    postedAt: daysAgo(2),
    expiryDate: daysFromNow(11),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'New Elective Courses for Next Semester',
    body: 'Registration for next semester elective courses is now open. New additions include Machine Learning, Cloud Computing, and Digital Marketing. Register through ERP before April 30.',
    category: 'Academic',
    tags: ['ALL'],
    urgency: 'Normal',
    postedBy: 'Academic Office',
    postedAt: daysAgo(3),
    expiryDate: daysFromNow(32),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Library Hours Extended During Exams',
    body: 'The central library will remain open from 7 AM to 11 PM during the examination period (April 14-25). Student ID is mandatory for entry after 8 PM.',
    category: 'Academic',
    tags: ['ALL'],
    urgency: 'Important',
    postedBy: 'Librarian Office',
    postedAt: daysAgo(1),
    expiryDate: daysFromNow(26),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Guest Lecture: Introduction to Quantum Computing',
    body: 'Dr. Ananya Rao from IIT Bombay will deliver a guest lecture on Quantum Computing fundamentals on April 5 at 2 PM in Auditorium A. All CS and IT students are encouraged to attend.',
    category: 'Academic',
    tags: ['CSE-3', 'CSE-4', 'IT-3', 'IT-4'],
    urgency: 'Normal',
    postedBy: 'CS Department',
    postedAt: daysAgo(10),
    expiryDate: daysAgo(2), // EXPIRED
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },

  // PLACEMENT (5)
  {
    title: 'TCS NQT Registration Open',
    body: 'TCS National Qualifier Test registrations are open for 2026 batch. Eligible branches: CSE, IT, ECE, EE. Minimum 60% aggregate required. Register on the TCS iON portal by April 7. Pre-placement talk on April 3.',
    category: 'Placement',
    tags: ['CSE-4', 'IT-4', 'ECE-4'],
    urgency: 'Urgent',
    postedBy: 'Placement Cell',
    postedAt: daysAgo(1),
    expiryDate: daysFromNow(9),
    isPinned: true,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Infosys Hiring Drive — April 12',
    body: 'Infosys will conduct an on-campus hiring drive on April 12 for Power Programmer and Systems Engineer roles. Eligible: CSE, IT students with 65%+ aggregate. Carry 2 passport photos and resume.',
    category: 'Placement',
    tags: ['CSE-4', 'IT-4'],
    urgency: 'Important',
    postedBy: 'Placement Cell',
    postedAt: daysAgo(2),
    expiryDate: daysFromNow(13),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Resume Building Workshop',
    body: 'The placement cell is organizing a resume building and LinkedIn optimization workshop on April 6, 10 AM, Seminar Hall 2. Open to all pre-final and final year students. Bring your laptop.',
    category: 'Placement',
    tags: ['ALL'],
    urgency: 'Normal',
    postedBy: 'Placement Cell',
    postedAt: daysAgo(4),
    expiryDate: daysFromNow(7),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Wipro Elite NLTH Results Announced',
    body: 'Results for the Wipro Elite NLTH exam conducted on March 20 have been announced. Selected students will receive emails directly. Check the placement portal for the list.',
    category: 'Placement',
    tags: ['CSE-4', 'IT-4'],
    urgency: 'Normal',
    postedBy: 'Placement Cell',
    postedAt: daysAgo(8),
    expiryDate: daysAgo(1), // EXPIRED
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Mock Interview Sessions — Week of April 7',
    body: 'Industry professionals from Deloitte and Capgemini will conduct mock interviews for final year students. Slots available April 7-11, 9 AM to 5 PM. Register on the placement portal.',
    category: 'Placement',
    tags: ['ALL'],
    urgency: 'Important',
    postedBy: 'Placement Cell',
    postedAt: daysAgo(3),
    expiryDate: daysFromNow(12),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },

  // EVENTS (5)
  {
    title: "Annual Cultural Fest 'Aarohan' — April 18-20",
    body: 'Aarohan 2026 is here! Three days of music, dance, drama, art, and coding competitions. Registrations open for all events. Solo and team categories available. Exciting prizes worth ₹2,00,000. Visit the Aarohan website for event details.',
    category: 'Events',
    tags: ['ALL'],
    urgency: 'Urgent',
    postedBy: 'Student Council',
    postedAt: daysAgo(1),
    expiryDate: daysFromNow(21),
    isPinned: true,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Hackathon: Code for Change',
    body: '24-hour hackathon on social impact themes. Teams of 3-4. Registration fee ₹200 per team. Prizes: ₹15,000, ₹10,000, ₹5,000. Register at the CS department office by April 12.',
    category: 'Events',
    tags: ['CSE-3', 'CSE-4', 'IT-3', 'IT-4'],
    urgency: 'Important',
    postedBy: 'Coding Club',
    postedAt: daysAgo(3),
    expiryDate: daysFromNow(16),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Photography Exhibition — Call for Entries',
    body: "The Photography Club is hosting its annual exhibition. Theme: 'Campus Life'. Submit up to 3 photos (digital or print) by April 9 to the Media Room. Best entries will be displayed in the main gallery.",
    category: 'Events',
    tags: ['ALL'],
    urgency: 'Normal',
    postedBy: 'Photography Club',
    postedAt: daysAgo(5),
    expiryDate: daysFromNow(11),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Blood Donation Camp — April 8',
    body: 'NSS Unit is organizing a blood donation camp on April 8, 9 AM to 3 PM at the Indoor Stadium. Donors will receive certificates and refreshments. Carry your college ID. Age 18+ only.',
    category: 'Events',
    tags: ['ALL'],
    urgency: 'Important',
    postedBy: 'NSS Unit',
    postedAt: daysAgo(4),
    expiryDate: daysFromNow(9),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'TEDx SAGI — Speaker Applications Open',
    body: "TEDx Sri Aurobindo Group of Institutions is looking for student speakers. Theme: 'Breaking Boundaries'. Submit your talk idea (max 500 words) via the Google Form linked on our Instagram page.",
    category: 'Events',
    tags: ['ALL'],
    urgency: 'Normal',
    postedBy: 'TEDx SAGI Team',
    postedAt: daysAgo(2),
    expiryDate: daysFromNow(31),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },

  // SCHOLARSHIPS (4)
  {
    title: 'State Government Merit Scholarship — Apply Now',
    body: 'Applications are open for the MP State Merit Scholarship 2025-26. Eligibility: Family income below ₹6 LPA, 75%+ in previous year. Apply on the scholarship portal. Last date: April 14. Documents required: income certificate, marksheet, Aadhaar.',
    category: 'Scholarships',
    tags: ['ALL'],
    urgency: 'Urgent',
    postedBy: 'Scholarship Cell',
    postedAt: daysAgo(2),
    expiryDate: daysFromNow(16),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'AICTE Pragati Scholarship for Girls',
    body: 'AICTE Pragati Scholarship offers ₹50,000/year for girl students in technical education. Apply through the National Scholarship Portal. Deadline April 19. Contact the scholarship cell for help with applications.',
    category: 'Scholarships',
    tags: ['ALL'],
    urgency: 'Important',
    postedBy: 'Scholarship Cell',
    postedAt: daysAgo(3),
    expiryDate: daysFromNow(21),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Research Fellowship for Final Year Students',
    body: 'IIT Delhi is offering summer research fellowships for final year B.Tech students. Stipend ₹25,000/month for 2 months. Apply with SOP and professor recommendation letter by May 8.',
    category: 'Scholarships',
    tags: ['CSE-4', 'ECE-4', 'ME-4'],
    urgency: 'Normal',
    postedBy: 'R&D Cell',
    postedAt: daysAgo(5),
    expiryDate: daysFromNow(41),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Sports Scholarship Applications Open',
    body: 'Students who have represented the university at state or national level sports events can apply for fee concession under the sports scholarship scheme. Submit achievement certificates to the sports office.',
    category: 'Scholarships',
    tags: ['ALL'],
    urgency: 'Normal',
    postedBy: 'Sports Department',
    postedAt: daysAgo(4),
    expiryDate: daysFromNow(26),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },

  // SPORTS (4)
  {
    title: 'Inter-College Cricket Tournament — Registrations Open',
    body: 'The annual inter-college cricket tournament begins April 12. Team registrations close April 10. Each team must have 15 players max. Entry fee ₹500 per team. Contact the sports secretary.',
    category: 'Sports',
    tags: ['ALL'],
    urgency: 'Important',
    postedBy: 'Sports Committee',
    postedAt: daysAgo(3),
    expiryDate: daysFromNow(11),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Yoga Session Every Morning — 6 AM',
    body: 'Daily yoga sessions are being conducted at the campus ground from 6 AM to 7 AM. Open to all students and faculty. Mats provided. No registration needed. Conducted by certified yoga instructor Ms. Priya.',
    category: 'Sports',
    tags: ['ALL'],
    urgency: 'Normal',
    postedBy: 'Wellness Committee',
    postedAt: daysAgo(7),
    expiryDate: daysFromNow(92),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Basketball Court Renovation Complete',
    body: 'The basketball court near Block C has been renovated with new flooring and hoops. Open for use from April 3. Please wear proper sports shoes. Court booking available through the sports office.',
    category: 'Sports',
    tags: ['ALL'],
    urgency: 'Normal',
    postedBy: 'Sports Department',
    postedAt: daysAgo(10),
    expiryDate: daysAgo(3), // EXPIRED
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'University Athletics Team Selection Trials',
    body: 'Selection trials for the university athletics team will be held on April 9 at the main ground. Events: 100m, 200m, 400m, long jump, shot put. Carry your sports kit and ID card. Report at 7 AM sharp.',
    category: 'Sports',
    tags: ['ALL'],
    urgency: 'Important',
    postedBy: 'Sports Department',
    postedAt: daysAgo(2),
    expiryDate: daysFromNow(10),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },

  // HOSTEL (4)
  {
    title: 'Hostel Mess Menu Updated',
    body: 'The hostel mess menu for April has been updated based on student feedback. Breakfast now includes South Indian options on Tuesdays and Thursdays. Check the mess notice board or the hostel app for the full menu.',
    category: 'Hostel',
    tags: ['ALL'],
    urgency: 'Normal',
    postedBy: 'Hostel Warden',
    postedAt: daysAgo(1),
    expiryDate: daysFromNow(31),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Hostel Room Allotment — Next Academic Year',
    body: 'Room allotment for the 2026-27 academic year will begin from April 18. Priority based on CGPA and seniority. Submit your room preference form at the hostel office by April 17.',
    category: 'Hostel',
    tags: ['ALL'],
    urgency: 'Important',
    postedBy: 'Hostel Administration',
    postedAt: daysAgo(2),
    expiryDate: daysFromNow(21),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Water Supply Disruption — April 6',
    body: 'Due to maintenance of the main water tank, water supply to Boys Hostel Block A and B will be disrupted from 10 AM to 4 PM on April 6. Please store water in advance. Sorry for the inconvenience.',
    category: 'Hostel',
    tags: ['ALL'],
    urgency: 'Urgent',
    postedBy: 'Hostel Maintenance',
    postedAt: daysAgo(1),
    expiryDate: daysFromNow(7),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Hostel Night Curfew Timing Reminder',
    body: 'Reminder: Hostel entry closes at 9:30 PM for all students. Late entry requires prior written permission from the warden. Repeated violations will result in hostel privileges being revoked.',
    category: 'Hostel',
    tags: ['ALL'],
    urgency: 'Normal',
    postedBy: 'Chief Warden',
    postedAt: daysAgo(6),
    expiryDate: daysFromNow(62),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },

  // GENERAL (3)
  {
    title: 'Campus Wi-Fi Password Changed',
    body: 'The campus Wi-Fi password has been updated for security. New credentials: Network: SAGI-Campus, Password: Spring@2026. Connect with your student email for authentication. Report connectivity issues to the IT helpdesk.',
    category: 'General',
    tags: ['ALL'],
    urgency: 'Important',
    postedBy: 'IT Department',
    postedAt: daysAgo(1),
    expiryDate: daysFromNow(31),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Canteen Timings Changed',
    body: 'Starting April 1, the main canteen will operate from 8 AM to 8 PM (extended by 1 hour). The juice counter near the library will open at 7:30 AM. New snack items have been added to the menu.',
    category: 'General',
    tags: ['ALL'],
    urgency: 'Normal',
    postedBy: 'Admin Office',
    postedAt: daysAgo(3),
    expiryDate: daysFromNow(31),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
  {
    title: 'Lost & Found: MacBook Charger',
    body: 'A MacBook charger (Type-C, 67W) was found near Seminar Hall 1 on March 28. Owner can collect it from the admin office (Room 102, Block A) with proper identification.',
    category: 'General',
    tags: ['ALL'],
    urgency: 'Normal',
    postedBy: 'Admin Office',
    postedAt: daysAgo(5),
    expiryDate: daysFromNow(11),
    isPinned: false,
    attachmentUrl: null,
    attachmentName: null,
  },
];

export const SEED_EVENTS: Omit<CalendarEvent, 'id'>[] = [
  { title: "TCS Pre-Placement Talk", category: "Deadline", date: daysFromNow(0), tags: ["CSE-4","IT-4","ECE-4"], color: "#10B981", description: "" },
  { title: "Resume Workshop", category: "Workshop", date: daysFromNow(1), tags: ["ALL"], color: "#F59E0B", description: "" },
  { title: "Athletics Selection Trials", category: "Sports", date: daysFromNow(2), tags: ["ALL"], color: "#F43F5E", description: "" },
  { title: "Blood Donation Camp", category: "Club", date: daysFromNow(4), tags: ["ALL"], color: "#EF4444", description: "" },
  { title: "Infosys On-Campus Drive", category: "Deadline", date: daysFromNow(6), tags: ["CSE-4","IT-4"], color: "#10B981", description: "" },
  { title: "Cricket Tournament Starts", category: "Sports", date: daysFromNow(7), tags: ["ALL"], color: "#F43F5E", description: "" },
  { title: "Scholarship Deadline (State)", category: "Deadline", date: daysFromNow(8), tags: ["ALL"], color: "#8B5CF6", description: "" },
  { title: "Mid-Semester Exams Begin", category: "Exam", date: daysFromNow(9), tags: ["ALL"], color: "#EF4444", description: "" },
  { title: "Hostel Room Allotment Starts", category: "Deadline", date: daysFromNow(10), tags: ["ALL"], color: "#06B6D4", description: "" },
  { title: "Aarohan Cultural Fest - Day 1", category: "Club", date: daysFromNow(11), tags: ["ALL"], color: "#8B5CF6", description: "" },
  { title: "Aarohan Cultural Fest - Day 2", category: "Club", date: daysFromNow(12), tags: ["ALL"], color: "#8B5CF6", description: "" },
  { title: "Aarohan Cultural Fest - Day 3", category: "Club", date: daysFromNow(13), tags: ["ALL"], color: "#8B5CF6", description: "" },
  { title: "AICTE Pragati Deadline", category: "Deadline", date: daysFromNow(14), tags: ["ALL"], color: "#8B5CF6", description: "" },
  { title: "Mid-Semester Exams End", category: "Exam", date: daysFromNow(19), tags: ["ALL"], color: "#EF4444", description: "" },
  { title: "TEDx SAGI Event", category: "Club", date: daysFromNow(25), tags: ["ALL"], color: "#F59E0B", description: "" },
];

export const SEED_ASSIGNMENTS: Omit<Assignment, 'id'>[] = [
  { title: "Binary Search Tree Implementation", course: "Data Structures (CS301)", dueDate: new Date("2026-04-10T00:00:00Z"), tags: ["CSE-3"], description: "Implement BST with insert, delete, search, and traversal operations. Submit code + report.", postedBy: "Faculty", postedAt: daysAgo(2) },
  { title: "Financial Statement Analysis Report", course: "Financial Accounting (BBA401)", dueDate: new Date("2026-04-12T00:00:00Z"), tags: ["BBA-4"], description: "Analyze financial statements of any listed Indian company. 15-page report with ratio analysis.", postedBy: "Faculty", postedAt: daysAgo(2) },
  { title: "Marketing Mix Case Study", course: "Marketing Management (BBA402)", dueDate: new Date("2026-04-08T00:00:00Z"), tags: ["BBA-4"], description: "Prepare a case study on the marketing mix of a startup company. Include 4Ps analysis.", postedBy: "Faculty", postedAt: daysAgo(2) },
  { title: "Database ER Diagram Project", course: "DBMS (CS302)", dueDate: new Date("2026-04-15T00:00:00Z"), tags: ["CSE-3"], description: "Design ER diagram for a hospital management system. Include at least 8 entities.", postedBy: "Faculty", postedAt: daysAgo(2) },
  { title: "Circuit Analysis Lab Report", course: "Network Analysis (ECE201)", dueDate: new Date("2026-04-09T00:00:00Z"), tags: ["ECE-2"], description: "Lab report for experiments 5-8. Include observations, calculations, and graphs.", postedBy: "Faculty", postedAt: daysAgo(2) },
  { title: "Business Communication Presentation", course: "Business Communication (BBA201)", dueDate: new Date("2026-04-11T00:00:00Z"), tags: ["BBA-2", "BBA-4"], description: "10-minute presentation on effective workplace communication. Teams of 3.", postedBy: "Faculty", postedAt: daysAgo(2) },
  { title: "Operating Systems Lab Assignment", course: "Operating Systems (CS401)", dueDate: new Date("2026-04-18T00:00:00Z"), tags: ["CSE-4"], description: "Implement process scheduling algorithms (FCFS, SJF, Round Robin). Compare performance.", postedBy: "Faculty", postedAt: daysAgo(2) },
  { title: "Entrepreneurship Business Plan", course: "Entrepreneurship (BBA403)", dueDate: new Date("2026-04-20T00:00:00Z"), tags: ["BBA-4"], description: "Develop a complete business plan for a tech startup. Include financial projections for 3 years.", postedBy: "Faculty", postedAt: daysAgo(2) },
  { title: "Machine Learning Mini Project", course: "ML (CS402)", dueDate: new Date("2026-04-22T00:00:00Z"), tags: ["CSE-4"], description: "Build a classification model using any real-world dataset. Submit Jupyter notebook + presentation.", postedBy: "Faculty", postedAt: daysAgo(2) },
  { title: "Digital Marketing Campaign Proposal", course: "Digital Marketing (BBA404)", dueDate: new Date("2026-04-25T00:00:00Z"), tags: ["BBA-4"], description: "Create a complete digital marketing campaign proposal for a local business.", postedBy: "Faculty", postedAt: daysAgo(2) },
];

export const SEED_USERS: AppUser[] = [
  {
    uid: "admin001",
    email: "admin@dashboard.com",
    name: "Dr. Admin",
    department: "Administration",
    year: 0,
    courses: [],
    isAdmin: true,
    tags: ["ALL"],
    subscribedCategories: ["Academic","Placement","Events","Scholarships","Sports","Hostel","General"],
    fcmToken: null
  },
  {
    uid: "student001",
    email: "alice@dashboard.com",
    name: "Alice Sharma",
    department: "BBA",
    year: 4,
    courses: ["Financial Accounting","Marketing Management","Entrepreneurship","Digital Marketing","Business Communication"],
    isAdmin: false,
    tags: ["BBA-4", "ALL"],
    subscribedCategories: ["Academic","Placement","Events","Scholarships"],
    fcmToken: null
  },
  {
    uid: "student002",
    email: "bob@dashboard.com",
    name: "Bob Patel",
    department: "CSE",
    year: 3,
    courses: ["Data Structures","DBMS","Computer Networks"],
    isAdmin: false,
    tags: ["CSE-3", "ALL"],
    subscribedCategories: ["Academic","Placement","Events"],
    fcmToken: null
  },
];
